import processing.core.PApplet;

/**
 * Created with IntelliJ IDEA.
 * User: mari
 * Date: 4/6/12
 * Time: 3:30 PM
 * DO NOT EDIT THIS FILE - CREATE A COPY OF IT
 *    See "public class SketchTemplate" above? This MUST be named the same as the file
 *    so if the new sketch file is named HumanFlag.java, the class must be named HumanFlag
 *    ... recommend right-clicking the class item in the file list to the right and doing Refactor: Copy
 *    ... and giving it a new name there, the thing is that the Refactor/Copy dialog only accepts valid names.
 * DOCS: http://www.slideshare.net/eskimoblood/processing-in-intellij
 * especially slide 22
 * To run sketches in IntelliJ, go to the Edit Configurations thing in the Run menu or toolbar
 *    ... and add as an APPLET - the sketch classes will be listed automatically
 */


public class BezierCurveTest extends PApplet {

    // DO NOT EDIT THIS FILE - CREATE A COPY OF IT
    //    See "public class SketchTemplate" above? This MUST be named the same as the file
    //    so if the new sketch file is named HumanFlag.java, the class must be named HumanFlag
    //    ... recommend right-clicking the class item in the file list to the right and doing Refactor: Copy
    //    ... and giving it a new name there, the thing is that the Refactor/Copy dialog only accepts valid names.
    // DOCS: http://www.slideshare.net/eskimoblood/processing-in-intellij
    // especially slide 22
    // To run sketches in IntelliJ, go to the Edit Configurations thing in the Run menu or toolbar
    //    ... and add as an APPLET - the sketch classes will be listed automatically

    // the normal Processing setup function.
    // Needs to state the "public" keyword since we're doing this outside the Processing IDE
        // - the Processing IDE does this automatically behind the scenes ...
    public void setup( )
    {
        size(150, 150);
        background(255);
        smooth();

        ellipse(50, 75, 5, 5); // endpoints of curve
        ellipse(100, 75, 5, 5);
        fill(255, 0, 0);
        ellipse(25, 25, 5, 5);  // control points
        ellipse(125, 25, 5, 5);
        noFill();
        stroke(0);
        bezier(50, 75, 25, 25, 125, 25, 100, 75);
    }

    public void draw() {

    }
}

