import processing.core.PApplet;

// DO NOT EDIT THIS FILE - CREATE A COPY OF IT

// DOCS: http://www.slideshare.net/eskimoblood/processing-in-intellij
// especially slide 22

/**
 * Created with IntelliJ IDEA.
 * User: mari
 * Date: 4/6/12
 * Time: 3:30 PM
 * DO NOT EDIT THIS FILE - CREATE A COPY OF IT
 *
 * DOCS: http://www.slideshare.net/eskimoblood/processing-in-intellij
 * especially slide 22
 */
public class SketchTemplate extends PApplet {

    // DO NOT EDIT THIS FILE - CREATE A COPY OF IT

    // DOCS: http://www.slideshare.net/eskimoblood/processing-in-intellij
    // especially slide 22

    // the normal Processing setup function.
    // Needs to state the "public" keyword since we're doing this outside the Processing IDE
        // - the Processing IDE does this automatically behind the scenes ...
    public void setup() {

    }

    public void draw() {

    }
}
